# Generated by Django 2.0.6 on 2018-07-20 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 7, 20, 10, 52, 19, 3120, tzinfo=utc))),
            ],
        ),
    ]
