# Generated by Django 2.0.6 on 2018-07-23 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request_fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_services',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 6, 59, 51, 88, tzinfo=utc)),
        ),
    ]
